FROM postgres:17-alpine
RUN apk add --no-cache git
COPY . /pggit/
WORKDIR /pggit
ENV POSTGRES_DB=pggit_test
ENV POSTGRES_USER=pggit_test  
ENV POSTGRES_PASSWORD=test
ENV POSTGRES_HOST_AUTH_METHOD=trust

RUN echo '#!/bin/sh' > /docker-entrypoint-initdb.d/01-init.sh \
    && echo 'cd /pggit/sql && psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f install.sql' >> /docker-entrypoint-initdb.d/01-init.sh \
    && chmod +x /docker-entrypoint-initdb.d/01-init.sh