-- ============================================================================
-- Phase 8: Week 1 - Alert Delivery System (Greenfield Schema)
-- ============================================================================
-- Purpose: Create independent alert delivery infrastructure
-- Design: Clean greenfield schema completely independent of Week 3/4
-- Date: 2025-12-27
-- Status: Production-ready implementation
-- ============================================================================

-- ============================================================================
-- TABLE: alert_delivery_queue
-- ============================================================================
-- Purpose: Queue alerts for delivery with retry tracking
-- Scope: All alerts generated by anomaly detection and correlation analysis
-- ============================================================================

CREATE TABLE IF NOT EXISTS pggit.alert_delivery_queue (
    delivery_id BIGSERIAL PRIMARY KEY,
    alert_id BIGINT NOT NULL,              -- Reference to Week 4 alert source
    webhook_id BIGINT NOT NULL,            -- Which webhook to deliver to
    message_body JSONB NOT NULL,           -- Alert content (flexible schema)

    -- Delivery status tracking
    delivery_status TEXT NOT NULL DEFAULT 'pending',  -- pending, delivered, failed, retrying

    -- Retry logic
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 3,
    next_retry_at TIMESTAMP,               -- When to retry (exponential backoff)

    -- Timestamps for tracking
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    attempted_at TIMESTAMP,                -- First delivery attempt
    delivered_at TIMESTAMP,                -- Successful delivery

    -- Constraints
    CONSTRAINT delivery_status_check CHECK (
        delivery_status IN ('pending', 'delivered', 'failed', 'retrying')
    ),
    CONSTRAINT retry_count_check CHECK (retry_count >= 0),
    CONSTRAINT max_retries_check CHECK (max_retries > 0)
);

-- Indexes for performance
CREATE INDEX idx_alert_delivery_queue_status
    ON pggit.alert_delivery_queue(delivery_status)
    WHERE delivery_status IN ('pending', 'retrying');

CREATE INDEX idx_alert_delivery_queue_next_retry
    ON pggit.alert_delivery_queue(next_retry_at)
    WHERE delivery_status = 'retrying' AND next_retry_at IS NOT NULL;

CREATE INDEX idx_alert_delivery_queue_webhook
    ON pggit.alert_delivery_queue(webhook_id)
    WHERE delivery_status IN ('pending', 'retrying');

CREATE INDEX idx_alert_delivery_queue_created
    ON pggit.alert_delivery_queue(created_at DESC);

-- ============================================================================
-- TABLE: alert_delivery_log
-- ============================================================================
-- Purpose: Audit trail of all delivery events
-- Tracking: Queued, attempted, delivered, failed, escalated
-- ============================================================================

CREATE TABLE IF NOT EXISTS pggit.alert_delivery_log (
    log_id BIGSERIAL PRIMARY KEY,
    delivery_id BIGINT NOT NULL,
    webhook_id BIGINT NOT NULL,

    -- Event tracking
    event_type TEXT NOT NULL,              -- queued, attempt, delivered, failed, escalated
    event_details JSONB,                   -- Error messages, HTTP status, etc.

    -- Timestamp
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Foreign key to delivery queue
    CONSTRAINT alert_delivery_log_fk
        FOREIGN KEY (delivery_id)
        REFERENCES pggit.alert_delivery_queue(delivery_id) ON DELETE CASCADE,

    -- Constraints
    CONSTRAINT event_type_check CHECK (
        event_type IN ('queued', 'attempt', 'delivered', 'failed', 'escalated')
    )
);

-- Indexes for audit trail queries
CREATE INDEX idx_alert_delivery_log_delivery
    ON pggit.alert_delivery_log(delivery_id);

CREATE INDEX idx_alert_delivery_log_webhook
    ON pggit.alert_delivery_log(webhook_id);

CREATE INDEX idx_alert_delivery_log_event_type
    ON pggit.alert_delivery_log(event_type);

CREATE INDEX idx_alert_delivery_log_created
    ON pggit.alert_delivery_log(created_at DESC);

-- ============================================================================
-- TABLE: alert_observers
-- ============================================================================
-- Purpose: Registry and health tracking for observer functions
-- Design: Monitor execution of queue, deliver, and escalate observers
-- ============================================================================

CREATE TABLE IF NOT EXISTS pggit.alert_observers (
    observer_id BIGSERIAL PRIMARY KEY,
    observer_type TEXT NOT NULL,           -- delivery, escalation, health

    -- Status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Execution tracking
    execution_count INTEGER NOT NULL DEFAULT 0,
    last_execution_at TIMESTAMP,
    last_error TEXT,

    -- Metadata
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT observer_type_check CHECK (
        observer_type IN ('delivery', 'escalation', 'health')
    ),
    CONSTRAINT observer_type_unique UNIQUE (observer_type)
);

-- Indexes for observer monitoring
CREATE INDEX idx_alert_observers_active
    ON pggit.alert_observers(is_active, observer_type);

CREATE INDEX idx_alert_observers_last_execution
    ON pggit.alert_observers(last_execution_at DESC);

-- ============================================================================
-- SUMMARY
-- ============================================================================
-- Created tables:
--   1. alert_delivery_queue - Queue for delivery with retry tracking
--   2. alert_delivery_log - Audit trail of all events
--   3. alert_observers - Observer registry and health tracking
--
-- Created indexes (10 total):
--   - 4 on alert_delivery_queue: status, next_retry, webhook, created
--   - 4 on alert_delivery_log: delivery_id, webhook_id, event_type, created
--   - 2 on alert_observers: active, last_execution
--
-- Schema design:
--   - Completely independent (no ALTER TABLE to Week 3/4)
--   - JSONB for flexible message schema
--   - Exponential backoff via next_retry_at timestamp
--   - Full audit trail via alert_delivery_log
--   - Observer health monitoring via alert_observers
--
-- Performance targets:
--   - INSERT to queue: <5ms
--   - Delivery status query: <1ms (indexed)
--   - Retry lookup: <1ms (indexed on next_retry_at)
--   - View queries: <5ms
-- ============================================================================
