#!/bin/bash
# create_extension_sql.sh
#
# Consolidates all pgGit SQL files referenced in install.sql into a single
# extension SQL file (pggit--1.0.0.sql) suitable for PostgreSQL extension system.
#
# This script:
# 1. Processes sql/install.sql
# 2. Follows all \i (include) directives
# 3. Removes psql meta-commands (\echo)
# 4. Adds dependency checking for pgcrypto
# 5. Outputs a consolidated pggit--1.0.0.sql file
#
# Usage: ./scripts/create_extension_sql.sh

set -e  # Exit on error

# Configuration
SQL_DIR="sql"
INSTALL_FILE="$SQL_DIR/install.sql"
OUTPUT_FILE="pggit--1.0.0.sql"
TEMP_FILE=$(mktemp)

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== pgGit Extension SQL Consolidation ===${NC}"
echo ""

# Check that we're in the pgGit root directory
if [ ! -f "$INSTALL_FILE" ]; then
    echo -e "${RED}Error: $INSTALL_FILE not found${NC}"
    echo "Please run this script from the pgGit root directory"
    exit 1
fi

echo -e "${YELLOW}Step 1: Reading $INSTALL_FILE${NC}"

# Write extension header
cat > "$TEMP_FILE" <<'EOF'
-- pggit--1.0.0.sql
--
-- pgGit: Git-like version control for PostgreSQL schemas
--
-- This file is generated by scripts/create_extension_sql.sh
-- Do not edit manually - edit the source files in sql/ instead
--
-- Installation: CREATE EXTENSION pggit;
--
-- For documentation, see: docs/README.md

-- Ensure required extensions are installed
-- pgGit requires pgcrypto for UUID and cryptographic functions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- pgGit Extension Installation
-- Consolidated from multiple SQL files

EOF

# Track included files
declare -a included_files=()

echo -e "${YELLOW}Step 2: Processing SQL files${NC}"

# Process install.sql line by line
while IFS= read -r line; do
    # Skip \echo commands (psql meta-commands)
    if [[ $line =~ ^\\echo ]]; then
        continue
    fi

    # Handle \i directives (include files)
    if [[ $line =~ ^\\i[[:space:]]+(.+)$ ]]; then
        include_file="${BASH_REMATCH[1]}"
        include_path="$SQL_DIR/$include_file"

        if [ ! -f "$include_path" ]; then
            echo -e "${RED}Warning: Referenced file not found: $include_path${NC}"
            continue
        fi

        echo "  Including: $include_file"
        included_files+=("$include_file")

        # Add section header
        echo "" >> "$TEMP_FILE"
        echo "-- ========================================" >> "$TEMP_FILE"
        echo "-- File: $include_file" >> "$TEMP_FILE"
        echo "-- ========================================" >> "$TEMP_FILE"
        echo "" >> "$TEMP_FILE"

        # Append the file contents
        cat "$include_path" >> "$TEMP_FILE"
        echo "" >> "$TEMP_FILE"

    else
        # Regular SQL line (not \i or \echo)
        if [[ -n "$line" ]]; then
            echo "$line" >> "$TEMP_FILE"
        fi
    fi
done < "$INSTALL_FILE"

# Add footer comment
cat >> "$TEMP_FILE" <<EOF

-- ========================================
-- End of pgGit Extension Installation
-- ========================================
--
-- Installation complete!
--
-- Quick start:
--   SELECT * FROM pggit.database_size_overview;
--   SELECT * FROM pggit.generate_pruning_recommendations();
--   SELECT * FROM pggit.top_space_consumers;
--
-- For full documentation, see docs/README.md
EOF

echo ""
echo -e "${YELLOW}Step 3: Validating generated SQL${NC}"

# Basic validation - check for common issues
if grep -q '\\echo' "$TEMP_FILE"; then
    echo -e "${YELLOW}Warning: Found \\echo commands in output (should be removed)${NC}"
fi

if grep -q '\\i ' "$TEMP_FILE"; then
    echo -e "${YELLOW}Warning: Found \\i directives in output (should be expanded)${NC}"
fi

# Count key elements
schema_count=$(grep -c "CREATE SCHEMA" "$TEMP_FILE" || true)
function_count=$(grep -c "CREATE OR REPLACE FUNCTION" "$TEMP_FILE" || true)
trigger_count=$(grep -c "CREATE EVENT TRIGGER" "$TEMP_FILE" || true)
table_count=$(grep -c "CREATE TABLE" "$TEMP_FILE" || true)

echo "  Schemas: $schema_count"
echo "  Functions: $function_count"
echo "  Event Triggers: $trigger_count"
echo "  Tables: $table_count"

echo ""
echo -e "${YELLOW}Step 4: Writing output file${NC}"

# Move temp file to final location
mv "$TEMP_FILE" "$OUTPUT_FILE"

# Set readable permissions for the output file
chmod 644 "$OUTPUT_FILE"

file_size=$(stat -f%z "$OUTPUT_FILE" 2>/dev/null || stat -c%s "$OUTPUT_FILE")
file_lines=$(wc -l < "$OUTPUT_FILE")

echo "  Output: $OUTPUT_FILE"
echo "  Size: $file_size bytes"
echo "  Lines: $file_lines"
echo ""

echo -e "${GREEN}✓ Consolidation complete!${NC}"
echo ""
echo "Files included:"
for file in "${included_files[@]}"; do
    echo "  - $file"
done
echo ""
echo "Next steps:"
echo "  1. Review the generated $OUTPUT_FILE"
echo "  2. Test installation: psql -d testdb -c 'CREATE EXTENSION pggit;'"
echo "  3. Run user journey tests: cd tests/user-journey && docker-compose up"
echo ""
