-- pgGit v0.3.1 Phase 11: Advanced Reporting
-- HTML/Markdown reports, schema evolution timelines, comprehensive analytics

-- ============================================================================
-- FUNCTION: pggit.generate_html_diff_report()
-- ============================================================================
-- Generate HTML-formatted schema comparison report
-- Returns: Self-contained HTML with styling

CREATE OR REPLACE FUNCTION pggit.generate_html_diff_report(
    p_branch_a text,
    p_branch_b text
)
RETURNS text AS $$
DECLARE
    v_diff jsonb;
    v_impact jsonb;
    v_html text;
    v_added integer;
    v_removed integer;
    v_modified integer;
    v_breaking integer;
    v_compatible integer;
BEGIN
    -- Get analysis
    v_diff := pggit.compare_schemas(p_branch_a, p_branch_b);
    v_impact := pggit.assess_migration_impact(v_diff);

    -- Extract counts
    v_added := COALESCE((v_diff->'summary'->>'added')::integer, 0);
    v_removed := COALESCE((v_diff->'summary'->>'removed')::integer, 0);
    v_modified := COALESCE((v_diff->'summary'->>'modified')::integer, 0);
    v_breaking := COALESCE((v_impact->>'breaking_changes')::integer, 0);
    v_compatible := COALESCE((v_impact->>'compatible_changes')::integer, 0);

    -- Generate HTML
    v_html := format(
        E'<!DOCTYPE html>\n' ||
        E'<html>\n' ||
        E'<head>\n' ||
        E'  <meta charset="UTF-8">\n' ||
        E'  <title>Schema Diff Report: %s → %s</title>\n' ||
        E'  <style>\n' ||
        E'    body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }\n' ||
        E'    .container { background: white; padding: 20px; border-radius: 8px; }\n' ||
        E'    h1 { color: #333; border-bottom: 3px solid #0066cc; padding-bottom: 10px; }\n' ||
        E'    .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 20px 0; }\n' ||
        E'    .metric { padding: 15px; border-left: 4px solid #0066cc; background: #f9f9f9; }\n' ||
        E'    .metric-value { font-size: 28px; font-weight: bold; color: #0066cc; }\n' ||
        E'    .metric-label { color: #666; margin-top: 5px; }\n' ||
        E'    .added { border-left-color: #28a745; }\n' ||
        E'    .added .metric-value { color: #28a745; }\n' ||
        E'    .removed { border-left-color: #dc3545; }\n' ||
        E'    .removed .metric-value { color: #dc3545; }\n' ||
        E'    .modified { border-left-color: #ffc107; }\n' ||
        E'    .modified .metric-value { color: #ffc107; }\n' ||
        E'    .risk-high { color: #dc3545; font-weight: bold; }\n' ||
        E'    .risk-medium { color: #ffc107; font-weight: bold; }\n' ||
        E'    .risk-low { color: #28a745; font-weight: bold; }\n' ||
        E'    .assessment { margin: 20px 0; padding: 15px; background: #f0f7ff; border-left: 4px solid #0066cc; }\n' ||
        E'    .timestamp { color: #999; font-size: 12px; }\n' ||
        E'  </style>\n' ||
        E'</head>\n' ||
        E'<body>\n' ||
        E'  <div class="container">\n' ||
        E'    <h1>Schema Comparison Report</h1>\n' ||
        E'    <p>%s → %s</p>\n' ||
        E'    <p class="timestamp">Generated: %s</p>\n' ||
        E'\n' ||
        E'    <h2>Summary</h2>\n' ||
        E'    <div class="summary">\n' ||
        E'      <div class="metric added">\n' ||
        E'        <div class="metric-value">%s</div>\n' ||
        E'        <div class="metric-label">Added Objects</div>\n' ||
        E'      </div>\n' ||
        E'      <div class="metric removed">\n' ||
        E'        <div class="metric-value">%s</div>\n' ||
        E'        <div class="metric-label">Removed Objects</div>\n' ||
        E'      </div>\n' ||
        E'      <div class="metric modified">\n' ||
        E'        <div class="metric-value">%s</div>\n' ||
        E'        <div class="metric-label">Modified Objects</div>\n' ||
        E'      </div>\n' ||
        E'    </div>\n' ||
        E'\n' ||
        E'    <h2>Impact Assessment</h2>\n' ||
        E'    <div class="assessment">\n' ||
        E'      <p><strong>Feasibility:</strong> %s</p>\n' ||
        E'      <p><strong>Risk Level:</strong> <span class="risk-%s">%s</span></p>\n' ||
        E'      <p><strong>Breaking Changes:</strong> %s</p>\n' ||
        E'      <p><strong>Compatible Changes:</strong> %s</p>\n' ||
        E'      <p><strong>Estimated Effort:</strong> %s</p>\n' ||
        E'    </div>\n' ||
        E'\n' ||
        E'    <hr>\n' ||
        E'    <p class="timestamp">Report generated by pgGit v0.3.1</p>\n' ||
        E'  </div>\n' ||
        E'</body>\n' ||
        E'</html>',
        p_branch_a, p_branch_b,
        p_branch_a, p_branch_b,
        NOW()::text,
        v_added, v_removed, v_modified,
        v_impact->>'feasibility',
        LOWER(v_impact->>'risk_level'),
        v_impact->>'risk_level',
        v_breaking,
        v_compatible,
        v_impact->>'estimated_effort'
    );

    RAISE NOTICE 'generate_html_diff_report: Generated HTML report for % → %', p_branch_a, p_branch_b;

    RETURN v_html;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- FUNCTION: pggit.generate_markdown_diff_report()
-- ============================================================================
-- Generate Markdown-formatted schema comparison report
-- GitHub/GitLab compatible format

CREATE OR REPLACE FUNCTION pggit.generate_markdown_diff_report(
    p_branch_a text,
    p_branch_b text
)
RETURNS text AS $$
DECLARE
    v_diff jsonb;
    v_impact jsonb;
    v_markdown text;
    v_added integer;
    v_removed integer;
    v_modified integer;
    v_breaking integer;
    v_compatible integer;
BEGIN
    -- Get analysis
    v_diff := pggit.compare_schemas(p_branch_a, p_branch_b);
    v_impact := pggit.assess_migration_impact(v_diff);

    -- Extract counts
    v_added := COALESCE((v_diff->'summary'->>'added')::integer, 0);
    v_removed := COALESCE((v_diff->'summary'->>'removed')::integer, 0);
    v_modified := COALESCE((v_diff->'summary'->>'modified')::integer, 0);
    v_breaking := COALESCE((v_impact->>'breaking_changes')::integer, 0);
    v_compatible := COALESCE((v_impact->>'compatible_changes')::integer, 0);

    -- Generate Markdown
    v_markdown := format(
        E'# Schema Comparison Report\n' ||
        E'\n' ||
        E'**From:** `%s`\n' ||
        E'**To:** `%s`\n' ||
        E'**Generated:** %s\n' ||
        E'\n' ||
        E'## Summary\n' ||
        E'\n' ||
        E'| Metric | Count |\n' ||
        E'|--------|-------|\n' ||
        E'| Added Objects | %s |\n' ||
        E'| Removed Objects | %s |\n' ||
        E'| Modified Objects | %s |\n' ||
        E'\n' ||
        E'## Impact Assessment\n' ||
        E'\n' ||
        E'- **Feasibility:** %s\n' ||
        E'- **Risk Level:** %s\n' ||
        E'- **Estimated Effort:** %s\n' ||
        E'\n' ||
        E'## Change Categorization\n' ||
        E'\n' ||
        E'| Category | Count |\n' ||
        E'|----------|-------|\n' ||
        E'| Breaking Changes | %s |\n' ||
        E'| Compatible Changes | %s |\n' ||
        E'\n' ||
        E'---\n' ||
        E'\n' ||
        E'*Report generated by [pgGit](https://github.com/anthropics/pggit) v0.3.1*\n',
        p_branch_a, p_branch_b,
        NOW()::text,
        v_added, v_removed, v_modified,
        v_impact->>'feasibility',
        v_impact->>'risk_level',
        v_impact->>'estimated_effort',
        v_breaking, v_compatible
    );

    RAISE NOTICE 'generate_markdown_diff_report: Generated Markdown report for % → %', p_branch_a, p_branch_b;

    RETURN v_markdown;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- FUNCTION: pggit.get_schema_evolution_timeline()
-- ============================================================================
-- Return schema change history over time period

CREATE OR REPLACE FUNCTION pggit.get_schema_evolution_timeline(
    p_branch_name text,
    p_days integer DEFAULT 30
)
RETURNS jsonb AS $$
DECLARE
    v_timeline jsonb := '{"events": []}'::jsonb;
    v_change RECORD;
    v_event_count integer := 0;
BEGIN
    -- Get schema diffs for branch in time period
    FOR v_change IN
        SELECT
            sd.id,
            sd.created_at,
            sd.added_count,
            sd.removed_count,
            sd.modified_count,
            sd.branch_a,
            sd.branch_b
        FROM pggit.schema_diffs sd
        WHERE (sd.branch_a = p_branch_name OR sd.branch_b = p_branch_name)
          AND sd.created_at > NOW() - (p_days || ' days')::interval
        ORDER BY sd.created_at DESC
    LOOP
        v_timeline := jsonb_set(
            v_timeline,
            '{events}',
            v_timeline->'events' || jsonb_build_object(
                'timestamp', v_change.created_at::text,
                'added', v_change.added_count,
                'removed', v_change.removed_count,
                'modified', v_change.modified_count,
                'from_branch', v_change.branch_a,
                'to_branch', v_change.branch_b
            )
        );
        v_event_count := v_event_count + 1;
    END LOOP;

    -- Add summary
    v_timeline := jsonb_set(v_timeline, '{branch}', to_jsonb(p_branch_name));
    v_timeline := jsonb_set(v_timeline, '{period_days}', to_jsonb(p_days));
    v_timeline := jsonb_set(v_timeline, '{event_count}', to_jsonb(v_event_count));
    v_timeline := jsonb_set(v_timeline, '{start_date}', to_jsonb((NOW() - (p_days || ' days')::interval)::text));
    v_timeline := jsonb_set(v_timeline, '{end_date}', to_jsonb(NOW()::text));

    RAISE NOTICE 'get_schema_evolution_timeline: Retrieved % events for % over % days', v_event_count, p_branch_name, p_days;

    RETURN v_timeline;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- VIEWS: REPORTING & ANALYTICS
-- ============================================================================

CREATE OR REPLACE VIEW pggit.v_schema_reports_summary AS
SELECT
    'diff_reports' as report_type,
    COUNT(DISTINCT branch_a) as branches_compared,
    COUNT(*) as total_comparisons,
    MAX(created_at) as last_generated
FROM pggit.schema_diffs
UNION ALL
SELECT
    'migration_plans' as report_type,
    COUNT(DISTINCT source_branch) as branches_analyzed,
    COUNT(*) as total_plans,
    MAX(created_at) as last_generated
FROM pggit.migration_plans;

CREATE OR REPLACE VIEW pggit.v_schema_change_activity AS
SELECT
    branch_a as branch,
    DATE(created_at) as change_date,
    COUNT(*) as comparison_count,
    SUM(added_count) as total_added,
    SUM(removed_count) as total_removed,
    SUM(modified_count) as total_modified
FROM pggit.schema_diffs
GROUP BY branch_a, DATE(created_at)
ORDER BY branch_a, change_date DESC;

CREATE OR REPLACE VIEW pggit.v_migration_effort_summary AS
SELECT
    source_branch,
    target_branch,
    (plan_json->>'step_count')::integer as step_count,
    plan_json->>'feasibility' as feasibility,
    created_at
FROM pggit.migration_plans
ORDER BY created_at DESC;

-- ============================================================================
-- END OF PHASE 11 TIER 1 - ADVANCED REPORTING
-- ============================================================================

